function [] = display_seq_par_range(fn, seq, isFEXI)

    Delta = seq.delta + seq.delta_pi;
    Ttrans = 2 * (2 * seq.delta_max + seq.delta_pi + seq.delta_c);

    if ~isfield(seq,'Vw')
        seq.Vw = nan;
    end
    
if isFEXI
    
    display(sprintf('%s: gc = %.1f-%.1f mT/m, qc = %.0f-%.0f m^-1, bf/b = %.f/%.f-%.f s/mm^2, tm = %.1f-%.1f ms, \n delta/Delta/Ttrans = %.1f/%.1f/%.1f ms, gf/g = %.1f/%.1f-%.1f mT/m',...
    fn, ...
    1e3*min(seq.gc_array(:)), 1e3*max(seq.gc_array(:)),...
    min(seq.qc_array(:)), max(seq.qc_array(:)),...
    1e-6*seq.bf, 1e-6*min(seq.b2(:)), 1e-6*max(seq.b2(:)), ...
    1e3*min(seq.tm(:)), 1e3*max(seq.tm(:)), ...
    1e3*seq.delta, 1e3*Delta, 1e3*Ttrans, ...
    1e3*seq.gf, 1e3*min(seq.g2(:)), 1e3*max(seq.g2(:)) ...
    ))
  
else
    display(sprintf('%s: gc = %.1f-%.1f mT/m, qc = %.0f-%.0f m^-1, b = %.f-%.f s/mm^2, Vw = %.1f 1/s^2, tm = %.1f-%.1f ms, \n delta/Delta = %.1f/%.1f-%.1f/%.1f ms, Ttrans = %.1f ms, g1 = %.1f-%.1f mT/m, g2 = %.1f-%.1f mT/m',...
    fn, ...
    1e3*min(seq.gc_array(:)), 1e3*max(seq.gc_array(:)),...
    min(seq.qc_array(:)), max(seq.qc_array(:)),...
    1e-6*min(seq.b(:)), 1e-6*max(seq.b(:)), ...
    seq.Vw, ...
    1e3*min(seq.tm(:)), 1e3*max(seq.tm(:)), ...
    1e3*min(seq.delta(:)), 1e3*max(Delta), 1e3*max(seq.delta(:)), 1e3*min(Delta(:)), ...
    (2*seq.delta_max+seq.delta_pi+seq.delta_c)*2e3, ...
    1e3*min(seq.g1(:)), 1e3*max(seq.g1(:)), ...
    1e3*min(seq.g2(:)), 1e3*max(seq.g2(:)) ...
    ))

end

